http:
  prefix: /where
  limit: 2gb
  tmpdir: ../tmp
  index: true

api:
  version:
    - v2

cors:
  origin:
    - http://localhost:5570

token:
  mode: symmetric
  issuer: http://localhost:5570/where
  audience: []

static:
  prefix: ''
  dir: ../public
